group "engine"

include "Engine"
include "Engine.Core"
include "Engine.Core.DirectX"
include "Engine.UI"
include "Engine.UI.Direct2D"
include "Engine.UI.GDI"
include "UnitTest"
include "UnitTest.Core"
include "UnitTest.UI"
include "PerformanceTest.UI"
