group "engine"

include "Core"
include "Engine"
include "Engine.DirectX"
include "Engine.OpenGL"
include "Engine.2D"
include "Engine.2D.DirectX"
include "Engine.3D"
include "Engine.3D.DirectX"
include "UI"
include "UI.DirectX"
include "UI.OpenGL"
