group "engine"

include "Core"
include "Engine"
include "Engine.DirectX"
include "Engine.OpenGL"
include "UI"
include "UI.DirectX"
include "UI.Direct2D"
include "UI.GDI"
include "UI.OpenGL"
include "UnitTest.Utils"
include "UnitTest.Engine"
include "UnitTest.Core"
include "UnitTest.UI"
include "PerformanceTest"
